spring:
  application:
    name: rmq-springboot
  rabbitmq:
      host: 180.76.114.178
      port: 5672
      username: leoli
      password: Y@yd@jtc@10086
      template:
        exchange: spring.topic